# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-06 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_token_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='uid',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
