# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0003_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='story',
            field=models.TextField(default=''),
        ),
    ]
