# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 10:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0004_section_story'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='story',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='writing.Story'),
        ),
    ]
