# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0005_auto_20161130_1030'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ('id',)},
        ),
        migrations.AlterField(
            model_name='section',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together=set([('story', 'text')]),
        ),
    ]
