# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-15 15:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('writing', '0007_story_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='shared_with',
            field=models.ManyToManyField(related_name='friend_of', to=settings.AUTH_USER_MODEL),
        ),
    ]
